

package io.github.kyay10.highkt.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.kyay10.highkt.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("category.kt")
  public void testCategory() {
    runTest("compiler-plugin/testData/box/category.kt");
  }

  @Test
  @TestMetadata("prompt.kt")
  public void testPrompt() {
    runTest("compiler-plugin/testData/box/prompt.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("compiler-plugin/testData/box/simple.kt");
  }

  @Test
  @TestMetadata("simple2.kt")
  public void testSimple2() {
    runTest("compiler-plugin/testData/box/simple2.kt");
  }

  @Test
  @TestMetadata("type_functions.kt")
  public void testType_functions() {
    runTest("compiler-plugin/testData/box/type_functions.kt");
  }

  @Test
  @TestMetadata("variance.kt")
  public void testVariance() {
    runTest("compiler-plugin/testData/box/variance.kt");
  }
}
