

package io.github.kyay10.highkt.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.kyay10.highkt.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("expandTo_mismatch.kt")
  public void testExpandTo_mismatch() {
    runTest("compiler-plugin/testData/diagnostics/expandTo_mismatch.kt");
  }

  @Test
  @TestMetadata("higher_order_type_function.kt")
  public void testHigher_order_type_function() {
    runTest("compiler-plugin/testData/diagnostics/higher_order_type_function.kt");
  }

  @Test
  @TestMetadata("rejects_invariance.kt")
  public void testRejects_invariance() {
    runTest("compiler-plugin/testData/diagnostics/rejects_invariance.kt");
  }
}
